greedyMusic/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('trackMusic.urls')),
    url(r'^admin/', admin.site.urls),
]

trackMusic/urls.py
from django.conf.urls import url
from . import views

app_name = 'trackmusic'
urlpatterns =  [
	url(r'^$', views.index, name='index'),
	url(r'^trackmusic/^$', views.index, name='index1'),
	url(r'^trackmusic/tracks$', views.tracks, name='tracks'),
	url(r'^trackmusic/tracks/([0-9]+)$', views.trackDetail, name='trackDetail'),
	url(r'^trackmusic/genres$', views.genres, name='genres'),
	url(r'^trackmusic/genres/([0-9]+)$', views.genre_detail, name='genre_detail'),
	url(r'^trackmusic/tracks/add$', views.addTrack, name='addTrack'),
	url(r'^trackmusic/tracks/edit/([0-9]+)$', views.editTrack, name='editTrack'),
	url(r'^trackmusic/genres/add$', views.addGenre, name='addGenre'),
	url(r'^trackmusic/genres/edit/([0-9]+)$', views.editGenre, name='editGenre'),
    url(r'^trackmusic/tracks/search$', views.searchTracks, name='searchTrack'),
    url(r'^trackmusic/genres/search$', views.searchGenres, name='searchGenre')

]

trackMusic/models.py
from __future__ import unicode_literals

from django.db import models

class Genre(models.Model):
	genre_name = models.CharField(max_length=200,unique=True)

	def __unicode__(self):
		return self.genre_name


class Track(models.Model):
	track_name = models.CharField(max_length=200,unique=True)
	rating = models.FloatField()

	def __unicode__(self):
		return self.track_name

class TrackGenreMap(models.Model):
	track_id = models.ForeignKey(Track)
	genre_id = models.ForeignKey(Genre)

	class Meta:
		unique_together = ("track_id", "genre_id")

	def __unicode__(self):
		return self.track_id.track_name + " :: " + self.genre_id.genre_name

trackMusic/forms.py
from django import forms
from .models import Genre


class AddTrackForm(forms.Form):
    track_name = forms.CharField(label='Track Name', max_length=200, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Track Name'}))
    track_rating = forms.FloatField(label='Rating', max_value=5,widget=forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Rating'}))
    genre = forms.ModelMultipleChoiceField(queryset=Genre.objects.all(), required=False, widget=forms.CheckboxSelectMultiple)


class AddGenreForm(forms.ModelForm):
    genre_name = forms.CharField(label='Genre Name', max_length=200, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Genre Name'}))

    class Meta:
        model = Genre
        fields = ['genre_name']

trackMusic/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Track, Genre, TrackGenreMap
from .forms import AddTrackForm, AddGenreForm
from django.template import loader
from .search import get_query
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    return HttpResponseRedirect('trackmusic/tracks')


def tracks(request):
    track_list = Track.objects.order_by('rating')[::-1]
    if 'page' in request.GET:
        page = request.GET['page']
        paginator = Paginator(track_list,5)
        try:
            tracks = paginator.page(page)
        except PageNotAnInteger:
            tracks = paginator.page(1)
        except EmptyPage:
            tracks = paginator.page(paginator.num_pages)
    else:
        paginator = Paginator(track_list,5)
        tracks = paginator.page(1)
    context = {'track_list': tracks}
    return render(request, 'trackMusic/index.html', context)


def trackDetail(request, track_id):
    track = get_object_or_404(Track, pk=track_id)
    return render(request, 'trackMusic/track_detail.html', {'track':track})


def genres(request):
    genre_list = Genre.objects.all()
    if 'page' in request.GET:
        page = request.GET['page']
        paginator = Paginator(genre_list,5)
        try:
            genres = paginator.page(page)
        except PageNotAnInteger:
            genres = paginator.page(1)
        except EmptyPage:
            genres = paginator.page(paginator.num_pages)
    else:
        paginator = Paginator(genre_list,5)
        genres = paginator.page(1)
    return render(request, 'trackMusic/genres.html', {'genre_list':genres})


def genre_detail(request, genre_id):
    genre = get_object_or_404(Genre, pk=genre_id)
    return render(request, 'trackMusic/genre_detail.html', {'genre':genre})


def addTrack(request):

    message = ""
    if request.method == 'POST':
        form = AddTrackForm(request.POST)
        if form.is_valid():
            track_name = form.cleaned_data['track_name']
            track_rating = form.cleaned_data['track_rating']
            genre = form.cleaned_data['genre']
            track = Track(track_name = track_name, rating=int(track_rating))
            track.save()

            for g in genre:
                trackgenremap = TrackGenreMap(track_id=track, genre_id=g)
                trackgenremap.save()
            message = "Great! Track Added Successfully."
    else:
        form = AddTrackForm()
    return render(request, 'trackMusic/addtrack.html',{'form':form, 'message':message})


def editTrack(request, track_id):
    return HttpResponse("genre detail will be shown here")


def addGenre(request):
    message= ""
    if request.method == 'POST':
        form = AddGenreForm(request.POST)
        if form.is_valid():
            form.save()
            message = "Great! Genre Added Successfully"
    else:
        form = AddGenreForm()
    return render(request, 'trackMusic/addgenre.html',{'form':form, 'message':message})


def editGenre(request, genre_id):
    return HttpResponse("genre detail will be shown here")


def searchTracks(request):
    query_string = ''
    found_entries = None
    search_fields=('track_name','rating')

    if ('q' in request.GET) and request.GET['q'].strip():

        query_string = request.GET['q']

        entry_query = get_query(query_string, search_fields)
        print entry_query
        found_entries = Track.objects.filter(entry_query)

        return render(request, 'trackMusic/index.html',
                         {'query_string': query_string, 'track_list': found_entries })

def searchGenres(request):
    query_string = ''
    found_entries = None
    search_fields=['genre_name']

    if ('q' in request.GET) and request.GET['q'].strip():

        query_string = request.GET['q']

        entry_query = get_query(query_string, search_fields)
        print entry_query
        found_entries = Genre.objects.filter(entry_query)

        return render(request, 'trackMusic/genres.html',
                         {'query_string': query_string, 'genre_list': found_entries })

trackMusic/templates/trackMusic/addgenre.html
{% extends 'trackMusic/base.html' %}
{% block tab %}
    {% include "trackMusic/tabs.html" with active_tab='add_genres' %}
{% endblock %}
{% block content %}
<div class="container" style="width:80%">
	<div class="page-header">
  <h1 style="text-align: -webkit-center;">Add Genre</h1>
	</div>

  <h1 style="text-align: -webkit-center; color:#00FF00">{{ message }}</h1>

    {{ form.non_field_errors }}
	<form class="form-horizontal" method="post" action="">
	{% csrf_token %}
  <div class="form-group">
      {{ form.genre_name.errors }}
    <label for="inputTrack" class="col-sm-2 control-label">Genre Name</label>
    <div class="col-sm-10">
      {{ form.genre_name }}
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Add Genre</button>

    </div>
  </div>
</form>

    <button class="btn btn-default btn-primary" onclick="window.location='/trackmusic/tracks'">Back To Tracks</button>
</div>

{% endblock %}

trackMusic/templates/trackMusic/addtrack.html
{% extends 'trackMusic/base.html' %}
{% block tab %}
    {% include "trackMusic/tabs.html" with active_tab='add_tracks' %}
{% endblock %}
{% block content %}
<div class="container" style="width:80%">
	<div class="page-header">
  <h1 style="text-align: -webkit-center;">Add Track</h1>
	</div>

  <h1 style="text-align: -webkit-center; color:#00FF00">{{ message }}</h1>

    {{ form.non_field_errors }}
	<form class="form-horizontal" method="post" action="">
	{% csrf_token %}
  <div class="form-group">
      {{ form.track_name.errors }}
    <label for="inputTrack" class="col-sm-2 control-label">Track Name</label>
    <div class="col-sm-10">
      {{ form.track_name }}
    </div>
  </div>
  <div class="form-group">
      {{ form.track_rating.errors }}
    <label for="inputRating" class="col-sm-2 control-label">Rating</label>
    <div class="col-sm-10">
      {{ form.track_rating }}
    </div>
  </div>

  <div class="form-group">
      {{ form.genre.errors }}
  <label for="inputGenre" class="col-sm-2 control-label">Genre</label>
  <div class="col-sm-10">
  {% for checkbox in form.genre %}
  	    {{ checkbox }}
  {% endfor %}
  </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Add Track</button>

    </div>
  </div>
</form>

    <button class="btn btn-default btn-primary" onclick="window.location='/trackmusic/tracks'">Back To Tracks</button>
</div>

{% endblock %}

trackMusic/templates/trackMusic/base.html
<!DOCTYPE html>
<html>

{% load staticfiles %}
<head>
	<title>Greedy Music</title>
	<link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
	<link href="{% static "bootstrap/css/star-rating.min.css" %}" rel="stylesheet">

</head>

<body class="container">
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><h3 style="margin-top: 0%;">Greedy Music</h3></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    {% block tab %}{% endblock %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
    <!--<div>
      <div style="text-align: -webkit-center;"><h1 style="font-size: 400%;margin-top: 0%;">Greedy Music</h1></div>
    </div>-->
  </nav>

  {% block content %}
  {% endblock %}

	
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "bootstrap/js/star-rating.min.js" %}"></script>
    <script>
		$(document).on('ready', function(){
    	$('.rating-loading').rating({displayOnly: true, step: 0.5});
		});
	</script>

</body>
</html>

trackMusic/templates/trackMusic/genre_detail.html
{% extends 'trackMusic/base.html' %}
{% block tab %}
    {% include "trackMusic/tabs.html" with active_tab='genres' %}
{% endblock %}
{% block content %}


<div class="page-header">
  <h1 style="text-align: -webkit-center;">{{ genre.genre_name }}</h1>
	</div>

<div class="clearfix visible-xs-block"></div>
<div class="container" style="width: 80%;">
<table class="table">

 {% if genre.trackgenremap_set.all %}
 	<thead>
 		<tr>
 		<th>Track</th>
 		<th>Genre</th>
 		<th>Rating</th>
 		</tr>
 	</thead>
 	<tbody>
	{% for track in genre.trackgenremap_set.all %}
		<tr></tr>
			<td><a href="{% url 'trackmusic:trackDetail' track.track_id.id %}">{{ track.track_id.track_name }}</a></td>
			<td>
				{% for g in track.track_id.trackgenremap_set.all %}
					<a href="{% url 'trackmusic:genre_detail' g.genre_id.id %}">{{ g.genre_id.genre_name }}</a>
				{% endfor %}
			</td>
			<td> <input id="input-3" value="{{ track.track_id.rating }}" class="rating-loading" data-size="xs"></td>
		</tr>
	{% endfor %}
{% else %}
	<p>
		No Tracks are available for this genre.
	</p>
{% endif %}
</tbody>
</table>

</div>

<div>
	<button type="button" class="btn btn-primary btn-lg btn-block" onclick="window.location='/trackmusic/tracks/add'">Add New Track</button>
</div>

{% endblock %}

trackMusic/templates/trackMusic/genres.html
{% extends 'trackMusic/base.html' %}
{% block tab %}
    {% include "trackMusic/tabs.html" with active_tab='genres' %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-lg-4"></div>
  <div class="col-lg-4">
      <form id="searchform" action="{% url 'trackmusic:searchGenre' %}" method="get" accept-charset="utf-8">
    <div class="input-group">
      <input name="q" type="text" class="form-control" placeholder="Search for genre...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Go!</button>
      </span>

    </div>
      </form>
  </div>

</div>

<div class="clearfix visible-xs-block"></div>
<div class="container" style="width: 80%;">
    {% if query_string %}
        <h3>Result for the query: {{ query_string }}</h3>
    {% endif %}
<table class="table">

 {% if genre_list %}
 	<thead>
 		<tr>
 		<th>Genre</th>
 		<th>Total Songs</th>
 		</tr>
 	</thead>
 	<tbody>
	{% for genre in genre_list %}
		<tr></tr>
			<td><a href="{% url 'trackmusic:genre_detail' genre.id %}">{{ genre.genre_name }}</a></td>
			<td>
				{{ genre.trackgenremap_set.all|length }}
			</td>
		</tr>
	{% endfor %}
{% else %}
	<p>
		No Genre are available.
	</p>
{% endif %}
</tbody>
</table>

    <nav>
  <ul class="pager">
    {% if genre_list.has_previous %}
      <li><a href="?page={{ genre_list.previous_page_number }}">Previous</a></li>
      {% endif %}
      {% if genre_list.number %}
      <li class="current">
            Page {{ genre_list.number }} of {{ genre_list.paginator.num_pages }}.
        </li>
      {% endif %}
    {% if genre_list.has_next %}
      <li><a href="?page={{ genre_list.next_page_number }}">Next</a></li>
      {% endif %}
  </ul>
    </nav>

</div>

<div>
	<button type="button" class="btn btn-primary btn-lg btn-block" onclick="window.location='genres/add'">Add New Genre</button>
</div>

{% endblock %}

trackMusic/templates/trackMusic/index.html
{% extends 'trackMusic/base.html' %}
{% block tab %}
    {% include "trackMusic/tabs.html" with active_tab='tracks' %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-lg-4"></div>
  <div class="col-lg-4">
      <form id="searchform" action="{% url 'trackmusic:searchTrack' %}" method="get" accept-charset="utf-8">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search for music tracks...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Go!</button>
      </span>
      
    </div>
      </form>
  </div>
  
</div>

<div class="clearfix visible-xs-block"></div>
<div class="container" style="width: 80%;">

    {% if query_string %}
        <h3>Result for the query: {{ query_string }}</h3>
    {% endif %}
<table class="table">
 
 {% if track_list %}
 	<thead>
 		<tr>
 		<th>Track</th>
 		<th>Genre</th>
 		<th>Rating</th>
 		</tr>
 	</thead>
 	<tbody>
	{% for track in track_list %}
		<tr></tr>
			<td><a href="{% url 'trackmusic:trackDetail' track.id %}">{{ track.track_name }}</a></td>
			<td> 
				{% for genre in track.trackgenremap_set.all %}
					<a href="{% url 'trackmusic:genre_detail' genre.genre_id.id %}">{{ genre.genre_id.genre_name }}</a>
				{% endfor %}
			</td>
			<td> <input id="input-3" value="{{ track.rating }}" class="rating-loading" data-size="xs"></td>
		</tr>
	{% endfor %}
{% else %}
	<p>
		No Tracks are available.
	</p>
{% endif %}
</tbody>
</table>

    <nav>
  <ul class="pager">
    {% if track_list.has_previous %}
      <li><a href="?page={{ track_list.previous_page_number }}">Previous</a></li>
      {% endif %}
      {% if track_list.number %}
      <li class="current">
            Page {{ track_list.number }} of {{ track_list.paginator.num_pages }}.
        </li>
      {% endif %}
    {% if track_list.has_next %}
      <li><a href="?page={{ track_list.next_page_number }}">Next</a></li>
      {% endif %}
  </ul>
    </nav>

</div>

<div>
	<button type="button" class="btn btn-primary btn-lg btn-block" onclick="window.location='tracks/add'">Add New Track</button>
</div>

{% endblock %}

trackMusic/templates/trackMusic/tabs.html
<ul class="nav navbar-nav">
        <li class="{% if active_tab == 'tracks' %} active{% endif %}"><a href="/trackmusic/tracks">Tracks</a></li>
        <li class="{% if active_tab == 'genres' %} active{% endif %}"><a href="/trackmusic/genres" >Genres</a></li>
        <li class="{% if active_tab == 'add_tracks' %} active{% endif %}"><a href="/trackmusic/tracks/add" >Add Tracks</a></li>
        <li class="{% if active_tab == 'add_genres' %} active{% endif %}"><a href="/trackmusic/genres/add" >Add Genres</a></li>

</ul>

trackMusic/templates/trackMusic/track_detail.html
{% extends 'trackMusic/base.html' %}
{% block tab %}
    {% include "trackMusic/tabs.html" with active_tab='tracks' %}
{% endblock %}
{% block content %}

<div class="container" style="width:60%">
	<div class="page-header">
  <h1 style="text-align: -webkit-center;">Track Detail</h1>
	</div>
	<table class="table">
		<tr>
			<td><b>Track Name:</b></td>
			<td>{{ track.track_name }}</td>
		</tr>
		<tr>
			<td><b>Track Genres:</b></td>
			<td>
				{% for genre in track.trackgenremap_set.all %}
					{{ genre.genre_id.genre_name }}
				{% endfor %}
			</td>
		</tr>
		<tr>
			<td><b>Track Rating:</b></td>
			<td><input id="input-3" value="{{ track.rating }}" class="rating-loading" data-size="sm"></td>
		</tr>
		<tr>
			<td><a href="/trackmusic/tracks" class="btn btn-primary btn-lg active" role="button">Back to tracks</a></td>
			<td></td>
		</tr>
	</table>
</div>

{% endblock %}